### ISSUE TITLE
helm repo add error

### ISSUE THREAD

**Issue by jinyu121** [8gears/n8n-helm-chart#77]
I want to add this helm chart via 

```bash
helm repo add n8n https://github.com/8gears/n8n-helm-chart 
```
Bug I got error:

```
Error: looks like "https://github.com/8gears/n8n-helm-chart" is not a valid chart repository or cannot be reached: failed to fetch https://github.com/8gears/n8n-helm-chart/index.yaml : 404 Not Found
```

I don't know what's the `index.yaml` is, but I can see some "professional" charts (such as bitnami and grafana) follow this template.

**Comment by Vad1mo** [comment]
> [!IMPORTANT]
> Starting Jan 2024, we serve Charts only as OCI artifacts.

**Comment by finkinfridom** [comment]
@Vad1mo that's clear, but maybe having some `troubleshoot` hints on the README would be great.
I switched yo OCI for your chart but now I'm having issues with Terraform `helm_release` and also when trying to use the `oci` registry through standard helm commands.
I think I'll move back to https registry and/or forking the official one because it was working smoothly (as this `oci` change is taking me days of troubleshooting now).
